language: java

jdk:
   - oraclejdk8

notifications:
  email:
    - adammblinderman@gmail.com

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/
 
env:
  global:
    - secure: "Dwb41Mdes13RFaB9Pf4fViLVt9U0NK8EvbzrD/GcWfHjKi1GpAgQ0WyUdQSKrxLViH2OL4BqQIQmOtugkW1rNQn/Gnnb4Hu4/rZ06+tLStcvmrm9+Pph++niqzCxZe206/VwDV393UVPWtVpFtbhDTaiJOf0dP+3BX7NAzqW+JU="
    
deploy:
  provider: releases 
  api_key: 
     secure: "MpLNWZbJE17d+ew3x4PvH7X/bspZPJM4pGQc8Sii6ufH7lQrnn+dBJAFItZ/IkZnoF6K+DdQsjhLtn+9PUhITx2BQdDfbmRwwuBsLUJmmn7KIUs4R0ONGjeUMtGuhAF7IcPF2MvfJvy
MMxCiXNgaIn2FKNYeJd4UwhEn64/2LvVmS77Ez9eTQIYDNA7c4XOJ/JEfj4mOcGFTJ+ZZZEmWYWWr31ztBpzTPdpCHPrEYkfj6yWhanbKGrNJ9Irexi2mUyLCPIzCRVy6NmsLfRNhK4LjI4bIxYlqm
dDQruqe12tiIYXCL2lZcSfW2aT6CIbo3MIAsMML8NIT2sUMiWE8hHhmlecwQxqrUrBVkCSzkHqKzS0GuUFfU2TUAJnxfFhxMkG6bgRM7kUn3ukG0ISc/g7cA0gXDJGCDabfDcfyg0Ff5LsNES88PyV
+eAlHZT7NpPwWFhPh26Z1nsmM5OcJeswiSA3Yr+tg9pao7+aORBqtd6qVrXf0foTb7NqAW3CXdNmS9CITgl6UPyWPgbunKT7U8kE0RI86ZSkHdKwwJ9TtV7/v4+Ujs+/waKyVzsXgroG2E8RnBYAQO
+ZQ24pEb5PUKVF2JPB78HBj411W10AkDinutd0kXgvZu5e3AzNL/pQ0ezI9gB1ECKCKnS9BtzkAeNzjk2sTsqwBKATJQVo="
  file: "target/jrs-rest-java-client-6.4.0-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    tags: false

after_success:
  - mvn assembly:single
  
after_deploy:
  - mvn clean cobertura:cobertura coveralls:cobertura